# Generated by Django 3.0.6 on 2020-11-18 18:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
