# Generated by Django 3.0.6 on 2020-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201119_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='comment',
            field=models.TextField(),
        ),
    ]
