# Generated by Django 3.0.6 on 2020-11-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201120_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='hello.jpg', null=True, upload_to=''),
        ),
    ]
